### ISSUE TITLE
set_light_dir() of sceneGE error

### ISSUE THREAD

**Issue by Zony-Zhao** [taichi-dev/taichi_three#1]
mesh.py in /example
set_light_dir() of sceneGE error
```
Internal Error occurred, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
[0mTraceback (most recent call last):
  File "test.py", line 16, in <module>
    scene.set_light_dir([1, 1, -1])
  File "C:\Python38\lib\site-packages\taichi_three\scene.py", line 18, in set_light_dir
    self.light_dir[None] = ldir
  File "C:\Python38\lib\site-packages\taichi\lang\util.py", line 209, in wrapped
    return func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\taichi\lang\matrix.py", line 354, in __setitem__
    self(i, j)[index] = item[i][j]
  File "C:\Python38\lib\site-packages\taichi\lang\util.py", line 209, in wrapped
    return func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\taichi\lang\expr.py", line 43, in __setitem__
    self.materialize_layout_callback()
  File "C:\Python38\lib\site-packages\taichi\lang\impl.py", line 177, in materialize
    taichi_lang_core.layout(layout)
```
RuntimeError: [struct_opengl.cpp:taichi::lang::opengl::OpenglStructCompiler::generate_types@71] SNodeType=dynamic not supported on OpenGL
![image](https://user-images.githubusercontent.com/50739849/85205124-bf340d00-b34b-11ea-8415-4d6d40265d9d.png)
![image](https://user-images.githubusercontent.com/50739849/85205137-d70b9100-b34b-11ea-9a58-e87b9897e2f0.png)

**Comment by archibate** [comment]
Thank for reporting this. Taichi THREE is not supported on the OpenGL backend yet. It may be supported after https://github.com/taichi-dev/taichi/pull/1256 is merged.
Sorry about the confusing master branch, now I opened another branch `dev` for development, and the examples in `master` should be valid now.

**Comment by Zony-Zhao** [comment]
I checked the master branch. The mesh.py and sceneGE.py is just what I want. If I want to render a simplest triangle, is there a robust way to access?
Thanks for your work!

**Comment by archibate** [comment]
Try this!
```py
import taichi as ti
import taichi_glsl as ts
import taichi_three as t3
ti.init(ti.cpu)

scene = t3.SceneGE()
pos1 = ti.Vector(3, ti.f32)
pos2 = ti.Vector(3, ti.f32)
pos3 = ti.Vector(3, ti.f32)
tris = ti.root.dynamic(ti.i, 2 ** 12)
tris.place(pos1, pos2, pos3)
tris_len = ti.var(ti.i32, ())

scene.add_triangle(pos1, pos2, pos3)
scene.set_light_dir([1, 1, -1])

@ti.func
def glTri(A, B, C):
    l = ti.atomic_add(tris_len[None], 1)
    pos1[l] = A
    pos2[l] = B
    pos3[l] = C

@ti.kernel
def init():
    glTri(ts.vec3(+0.0, +0.5, 0.0),
          ts.vec3(-0.5, -0.5, 0.0),
          ts.vec3(+0.5, -0.5, 0.0))

init()

gui = ti.GUI('Triangle', scene.res)
while gui.running:
    gui.running = not gui.get_event(ti.GUI.ESCAPE)
    scene.camera.from_mouse(gui)
    scene.render()
    gui.set_image(scene.img)
    gui.show()
```
(Note: require commit 1941110)

**Comment by Zony-Zhao** [comment]
It works!
