### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by yyf0202** [taichi-dev/taichi_three#13]
hi，here is the logs
 ~/taichi-works/taichi_three   master  sudo python3 setup.py build install
[Taichi] mode=release
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from taichi_three.version import version, taichi_version, taiglsl_version
  File "/Users/yangyifan/taichi-works/taichi_three/taichi_three/__init__.py", line 1, in <module>
    import taichi_glsl as ts
  File "/Library/Python/3.7/site-packages/taichi_glsl/__init__.py", line 5, in <module>
    import taichi as ti
  File "/Library/Python/3.7/site-packages/taichi/__init__.py", line 1, in <module>
    from .core import *
  File "/Library/Python/3.7/site-packages/taichi/core/__init__.py", line 1, in <module>
    from .util import *
  File "/Library/Python/3.7/site-packages/taichi/core/util.py", line 158, in <module>
    import_ti_core()
  File "/Library/Python/3.7/site-packages/taichi/core/util.py", line 47, in import_ti_core
    core.set_lib_dir(locale_encode(lib_dir))
  File "/Library/Python/3.7/site-packages/taichi/core/util.py", line 55, in locale_encode
    return s.encode(locale.getdefaultlocale()[1])
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/locale.py", line 568, in getdefaultlocale
    return _parse_localename(localename)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/locale.py", line 495, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

And my env info is：
[Taichi] version 0.6.29, llvm 10.0.0, commit f1bde29b, osx, python 3.7.3
[TaiGLSL] version 0.0.8
[Tai3D] version 0.0.3

**Comment by archibate** [comment]
Thank for reporting, this is probably a bug of Taichi. What's your output of running these commands:
```
echo LANG $LANG
echo LC_ALL $LC_ALL
locale
```
?

Does modifying `/Library/Python/3.7/site-packages/taichi/core/util.py` in line 55 from:
```py
  return s.encode(locale.getdefaultlocale()[1])
```
to
```py
  return s.encode()
```
fix the issue?

**Comment by yyf0202** [comment]
Thank for replying.
Modifying util.py does not work.
Follow the related issues,i fixed this error by exporting environment variables.

**Comment by archibate** [comment]
Great! Would you mind tell me what's your original value of that two environment variables?

**Comment by yyf0202** [comment]
Of course. The output is :
LANG
LC_ALL
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
