### ISSUE TITLE
Ball example running into AttributeError with correct dependencies

### ISSUE THREAD

**Issue by horuswoo** [taichi-dev/taichi_three#24]
Hi, I'm new to Taichi and was trying to run the `ball_simulation.py` example when I ran into this error:
```
py3.6 ❯ python ball_simulation.py
[Taichi] mode=release
[Taichi] preparing sandbox at /var/folders/bz/_53mkqhn6q79rk5qrfmz0jvc0000gn/T/taichi-jvhqp0hg
[Taichi] version 0.6.40, llvm 10.0.0, commit 78231814, osx, python 3.6.10
[TaiGLSL] version 0.0.10
[Tai3D] version 0.0.7
[Tai3D] Inputs are welcomed at https://github.com/taichi-dev/taichi_three
[Tai3D] Camera control hints: LMB to orbit, MMB to move, RMB to scale
[Taichi] Starting on arch=x64
[Taichi] materializing...
Traceback (most recent call last):
  File "ball_simulation.py", line 73, in <module>
    scene.render()
  File "/Users/horus/anaconda3/envs/py3.6/lib/python3.6/site-packages/taichi/lang/kernel.py", line 606, in __call__
    return self._primal(self._kernel_owner, *args, **kwargs)
  File "/Users/horus/anaconda3/envs/py3.6/lib/python3.6/site-packages/taichi/lang/kernel.py", line 501, in __call__
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/Users/horus/anaconda3/envs/py3.6/lib/python3.6/site-packages/taichi/lang/kernel.py", line 370, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "/Users/horus/anaconda3/envs/py3.6/lib/python3.6/site-packages/taichi/lang/kernel.py", line 367, in taichi_ast_generator
    compiled()
  File "/Users/horus/anaconda3/envs/py3.6/lib/python3.6/site-packages/taichi_three/scene.py", line 51, in render
    camera.render(self)
  File "/Users/horus/anaconda3/envs/py3.6/lib/python3.6/site-packages/taichi/lang/kernel.py", line 42, in decorated
    return fun.__call__(*args)
  File "/Users/horus/anaconda3/envs/py3.6/lib/python3.6/site-packages/taichi/lang/kernel.py", line 87, in __call__
    ret = self.compiled(*args)
  File "/Users/horus/anaconda3/envs/py3.6/lib/python3.6/site-packages/taichi_three/camera.py", line 112, in render
    model.set_view(self)  # sets up ModelView matrix
  File "/Users/horus/anaconda3/envs/py3.6/lib/python3.6/site-packages/taichi/lang/kernel.py", line 42, in decorated
    return fun.__call__(*args)
  File "/Users/horus/anaconda3/envs/py3.6/lib/python3.6/site-packages/taichi/lang/kernel.py", line 87, in __call__
    ret = self.compiled(*args)
  File "/Users/horus/anaconda3/envs/py3.6/lib/python3.6/site-packages/taichi_three/model.py", line 27, in set_view
    self.L2C[None] = camera.L2W[None].inverse() @ self.L2W[None]
  File "/Users/horus/anaconda3/envs/py3.6/lib/python3.6/site-packages/taichi/lang/kernel.py", line 616, in getattr
    x = super(cls, self).__getattribute__(item)
AttributeError: 'ScatterModel' object has no attribute 'L2C'
```

**Comment by archibate** [comment]
Thank for reporting! Fixing this bug now :rocket: Before that, you may use the previous version `pip install taichi_three==0.0.6` which should be functional in `ScatterModel`.

**Comment by archibate** [comment]
Forgot to mention, this is fixed in latest version!
