### ISSUE TITLE
blender addon install error

### ISSUE THREAD

**Issue by kphmd** [taichi-dev/taichi_three#37]
Modules Installed (Taichi-Blend) from '/Users/Taichi-Blend-osx-37.zip' into '/Users/Library/Application Support/Blender/2.91/scripts/addons'
Taichi-Blend package bundle at /Users/Library/Application Support/Blender/2.91/scripts/addons/Taichi-Blend/bundle-packages
Exception in module register(): /Users/Library/Application Support/Blender/2.91/scripts/addons/Taichi-Blend/__init__.py
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.91/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/Users/Library/Application Support/Blender/2.91/scripts/addons/Taichi-Blend/__init__.py", line 24, in register
    module.register()
  File "/Users/Library/Application Support/Blender/2.91/scripts/addons/Taichi-Blend/node_system/__init__.py", line 56, in register
    node_system.register()
  File "/Users/Library/Application Support/Blender/2.91/scripts/addons/Taichi-Blend/node_system/__init__.py", line 28, in register
    self.module.register_callback(self)
  File "/Users/Library/Application Support/Blender/2.91/scripts/addons/Taichi-Blend/node_system/material.py", line 34, in register_callback
    tina.register()
  File "/Users/Library/Application Support/Blender/2.91/scripts/addons/Taichi-Blend/bundle-packages/tina/__init__.py", line 21, in register
    from . import blend
  File "/Users/Library/Application Support/Blender/2.91/scripts/addons/Taichi-Blend/bundle-packages/tina/blend/__init__.py", line 128, in <module>
    class CustomDrawData:
  File "/Users/Library/Application Support/Blender/2.91/scripts/addons/Taichi-Blend/bundle-packages/tina/blend/__init__.py", line 157, in CustomDrawData
    '''))
  File "/Users/Library/Application Support/Blender/2.91/scripts/addons/Taichi-Blend/bundle-packages/tina/blend/__init__.py", line 109, in compile_shader
    raise RuntimeError(''.join(chr(infoLog[i]) for i in range(length[0])))
RuntimeError: ERROR: 0:11: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:12: Use of undeclared identifier 'color'
ERROR: 0:12: Use of undeclared identifier 'color'
ERROR: 0:13: Use of undeclared identifier 'color'

**Comment by archibate** [comment]
Hi, sorry for the delayed reply, does modifying `texture2D` to `texture` at line 153 of `__init__.py` fix the issue?

**Comment by kphmd** [comment]
> Hi, sorry for the delayed reply, does modifying `texture2D` to `texture` at line 153 of `__init__.py` fix the issue?

The issue is fixed.
