### ISSUE TITLE
Error at import

### ISSUE THREAD

**Issue by Dr-How** [taichi-dev/taichi_three#51]
```
[Taichi] version 0.9.2, llvm 10.0.0, commit 7a4d73cd, osx, python 3.9.10
[Tina] version 0.1.1
Traceback (most recent call last):
  File "/Users/haochen/Library/CloudStorage/Dropbox/Projects/Taichi/tina-test.py", line 2, in <module>
    import tina
  File "/usr/local/lib/python3.9/site-packages/tina/__init__.py", line 22, in <module>
    from .hacker import *
  File "/usr/local/lib/python3.9/site-packages/tina/hacker.py", line 8, in <module>
    and f(x, y, z))(ti.Matrix.element_wise_writeback_binary)) or setattr(
AttributeError: type object 'Matrix' has no attribute 'element_wise_writeback_binary'
```

**Comment by myheathcliff** [comment]
Have you solved this problem? I have the same problem too

**Comment by archibate** [comment]
Downgrade Taichi to 0.6.8 may help the problem.

**Comment by ritchesc** [comment]
I encounter the same  issue.
