### ISSUE TITLE
ModuleNotFoundError: No module named 'transformations'

### ISSUE THREAD

**Issue by hughkhu** [taichi-dev/taichi_three#54]
$ python docs/connect.py
[Taichi] mode=release
[Taichi] version 0.7.13, llvm 10.0.0, commit 26bda350, win, python 3.8.13
[Tina] version 0.1.1
[Tina] Taichi properties hacked
[Taichi] Starting on arch=cuda
[Taichi] materializing...
[Tina] Hint: MMB to orbit, Shift+MMB to pan, wheel to zoom
Traceback (most recent call last):
  File "docs/connect.py", line 18, in <module>
    scene.input(gui)
  File "G:\codes\taichi_three\tina\scene\raster.py", line 225, in input
    changed = self.control.apply_camera(self.engine)
  File "G:\codes\taichi_three\tina\util\control.py", line 117, in apply_camera
    view, proj = self.get_camera()
  File "G:\codes\taichi_three\tina\util\control.py", line 103, in get_camera
    from .matrix import lookat, orthogonal, perspective, affine
  File "G:\codes\taichi_three\tina\util\matrix.py", line 2, in <module>
    from transformations import quaternion_matrix, quaternion_multiply, quaternion_from_matrix
ModuleNotFoundError: No module named 'transformations'

- Version
python                  3.8.13               h6244533_0
taichi                    0.7.13                   pypi_0    pypi
taichi-tina             0.1.1                    pypi_0    pypi

- Platform
Windows 10

**Comment by hughkhu** [comment]
Solved by pip install transformations
